---
default_config:
logger:
  default: error
  logs:
    custom_components.gpodder: debug

gpodder:
  username: iantrich
  password: password
  sensor:
    - enabled: true
      name: My custom name
      device: gPodder device identifier